### ISSUE TITLE
how to get the 'yolov4-tiny.onnx'

### ISSUE THREAD

**Issue by ckysohandsome** [hafidh561/multi-camera-people-tracking#3]
Hello! Thank you very much for uploading the open source project! I encountered some problems while reproducing your project and would like to ask you for advice. Could you tell me how you trained your yolov4-tiny.onnx? Which network did you use? The onnx file that I trained using yolov4-tiny always has a dimension mismatch.

**Comment by hafidh561** [comment]
You can run my download_model.py to get yolov4-tiny.onnx, or you can check on these files there is a Google Drive link you can download manually. I use [YOLOv4 Tiny Model](https://github.com/AlexeyAB/darknet), and after that I convert it to ONNX with these [repository](https://github.com/Tianxiaomo/pytorch-YOLOv4)

**Comment by ckysohandsome** [comment]
> You can run my download_model.py to get yolov4-tiny.onnx, or you can check on these files there is a Google Drive link you can download manually. I use [YOLOv4 Tiny Model](https://github.com/AlexeyAB/darknet), and after that I convert it to ONNX with these [repository](https://github.com/Tianxiaomo/pytorch-YOLOv4)

Thank you very much for your reply! Your reply is of great help to me!
