### ISSUE TITLE
where is sample_video？

### ISSUE THREAD

**Issue by gsathinker** [hafidh561/multi-camera-people-tracking#4]
where is sample_video and the video in that？

**Comment by hafidh561** [comment]
https://www.epfl.ch/labs/cvlab/data/data-pom-index-php/

**Comment by gsathinker** [comment]
when run main.py
cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1268: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'

**Comment by hafidh561** [comment]
> when run main.py cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1268: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'

I think this error, because your opencv doesn't same my version, or there is prerequisites on opencv to install additonals package.
